import type { SiteConfig, SiteSelectorConfig } from "@/types/crawler";

const GWANGJU_DO_SELECTORS: SiteSelectorConfig = {
  list: [".board_list_body .body_row", "table tbody tr"],
  title: [".subject a", "td.subject a", "td a"],
  date: [".date", "td"],
  dateColumnIndex: 3,
  content: [".board_view_con", ".view_cont", ".boardContents", ".d_cont_description", ".bd_view_cont"],
};

const GWANGJU_ES_SELECTORS: SiteSelectorConfig = {
  list: [".board_list tbody tr", "table tbody tr"],
  title: ["td.subject a", "td a"],
  date: ["td"],
  dateColumnIndex: 4,
  content: [".board_view_contents", ".board_view_con", ".board_view"],
};

const JEONNAM_DO_SELECTORS: SiteSelectorConfig = {
  list: ["table tbody tr"],
  title: ["td.title a", "td.subject a"],
  date: ["td"],
  dateColumnIndex: 3,
  content: [".bbs_view_contnet", ".view_content", ".board_view_con"], // Note: 'contnet' matches the actual CSS class on jeonnam.go.kr (their typo)
};

const JEONNAM_SI_SELECTORS: SiteSelectorConfig = {
  list: [".bbs_list_n tbody tr", "table tbody tr"],
  title: [".td_subject a", "td a"],
  date: [".td_date", "td"],
  dateColumnIndex: 3,
  content: [
    ".bbs_content",
    ".text_viewbox",
    ".viewbox",
    ".view_box",
    ".board_cont",
    ".con_detail",
    ".show_info",
    ".view_content",
    ".contbox",
  ],
};

const SUNCHEON_SELECTORS: SiteSelectorConfig = {
  list: [".bbs_default tbody tr", "table tbody tr"],
  title: ["td.subject a", "td a"],
  date: ["td"],
  dateColumnIndex: 4,
  content: [".bbs_content_detail", ".view_content"],
};

const DAMYANG_SELECTORS: SiteSelectorConfig = {
  list: [".board_list li", "table tbody tr"],
  title: [".subject a", "a:first"],
  date: [".date", "td"],
  dateColumnIndex: 3,
  content: [".board_view_content", ".view_cont"],
};

const GOKSEONG_SELECTORS: SiteSelectorConfig = {
  list: [".board_list tbody tr", "table tbody tr"],
  title: ["td a"],
  date: ["td"],
  dateColumnIndex: 3,
  content: [".board_view_con", ".view_content"],
};

const HWASUN_SELECTORS: SiteSelectorConfig = {
  list: ["table tbody tr"],
  title: ["td a"],
  date: ["td"],
  dateColumnIndex: 3,
  content: [".boardR", ".view_content", ".board_contents"],
};

const HAENAM_SELECTORS: SiteSelectorConfig = {
  list: ["div.press_list > div.item", "ul.board_list li:not(.thead)", "table tbody tr"],
  title: ["div.right h4 a", "h4 a", "a:first", "td a"],
  date: ["span.date", ".date", ".day", "td"],
  dateColumnIndex: 0,
  content: [".data_cont", ".board_view"],
};

const YEONGGWANG_SELECTORS: SiteSelectorConfig = {
  list: [".board_list tbody tr", "table tbody tr"],
  title: ["td a"],
  date: ["td"],
  dateColumnIndex: 3,
  content: [".board_view_contents", ".board_view_content", ".view_content"],
};

const WANDO_SELECTORS: SiteSelectorConfig = {
  list: ["table tbody tr"],
  title: ["td a"],
  date: ["td"],
  dateColumnIndex: 3,
  content: [".board_cont", ".board_view", ".view_content"],
};

const MOKPO_SELECTORS: SiteSelectorConfig = {
  list: ["div.board_thumb > div.item"],
  title: ["h3", "a"],
  date: ["dd.date", ".date"],
  dateColumnIndex: 0,
  content: [".text_viewbox", ".viewbox", ".contbox", ".bbs_content", ".view_content"],
};

export const SITES: SiteConfig[] = [
  {
    id: "gwangju-city",
    name: "광주시청",
    type: "gwangju-do",
    listUrl: "https://www.gwangju.go.kr/boardList.do?pageId=www789&boardId=BD_0000000027",
    detailUrlTemplate: "https://www.gwangju.go.kr/boardView.do?pageId=www789&boardId=BD_0000000027&seq={id}",
    idPattern: /seq=(\d+)/,
    selectors: GWANGJU_DO_SELECTORS,
    paginationParam: "pageIndex",
  },
  {
    id: "donggu",
    name: "동구청",
    type: "gwangju-es-nolist",
    listUrl: "https://www.donggu.kr/board.es?mid=a10102040100&bid=0243",
    detailUrlTemplate: "https://www.donggu.kr/board.es?mid=a10102040100&bid=0243&act=view&list_no={id}",
    idPattern: /list_no=(\d+)/,
    selectors: GWANGJU_ES_SELECTORS,
    paginationParam: "nPage",
  },
  {
    id: "seogu",
    name: "서구청",
    type: "gwangju-es",
    listUrl: "https://www.seogu.gwangju.kr/board.es?mid=a10612000000&bid=0154",
    detailUrlTemplate: "https://www.seogu.gwangju.kr/board.es?mid=a10612000000&bid=0154&act=view&list_no={id}",
    idPattern: /list_no=(\d+)/,
    selectors: GWANGJU_ES_SELECTORS,
    paginationParam: "nPage",
  },
  {
    id: "namgu",
    name: "남구청",
    type: "namgu",
    listUrl: "https://www.namgu.gwangju.kr/api/eminwon/pressList.es?mid=a10605050000",
    detailUrlTemplate: "https://www.namgu.gwangju.kr/api/eminwon/pressList.es?mid=a10605050000&act=view&list_no={id}",
    idPattern: /list_no=(\d+)/,
    selectors: GWANGJU_ES_SELECTORS,
  },
  {
    id: "bukgu",
    name: "북구청",
    type: "gwangju-es-nolist",
    listUrl: "https://bukgu.gwangju.kr/board.es?mid=a10201020000&bid=0275",
    detailUrlTemplate: "https://bukgu.gwangju.kr/board.es?mid=a10201020000&bid=0275&act=view&list_no={id}",
    idPattern: /list_no=(\d+)/,
    selectors: GWANGJU_ES_SELECTORS,
    paginationParam: "nPage",
  },
  {
    id: "gwangsan",
    name: "광산구청",
    type: "gwangju-do",
    listUrl: "https://www.gwangsan.go.kr/boardList.do?boardId=REPORT_NEW&pageId=www16",
    detailUrlTemplate: "https://www.gwangsan.go.kr/boardView.do?boardId=REPORT_NEW&pageId=www16&seq={id}",
    idPattern: /seq=(\d+)/,
    selectors: GWANGJU_DO_SELECTORS,
    paginationParam: "pageIndex",
  },
  {
    id: "jeonnam-province",
    name: "전라남도청",
    type: "jeonnam-do",
    listUrl: "https://www.jeonnam.go.kr/M7116/boardList.do?menuId=jeonnam0202000000",
    detailUrlTemplate: "https://www.jeonnam.go.kr/M7116/boardView.do?menuId=jeonnam0202000000&seq={id}",
    idPattern: /seq=(\d+)/,
    selectors: JEONNAM_DO_SELECTORS,
    paginationParam: "pageIndex",
  },
  {
    id: "mokpo",
    name: "목포시청",
    type: "mokpo",
    listUrl: "https://www.mokpo.go.kr/www/mokpo_news/press_release",
    detailUrlTemplate: "https://www.mokpo.go.kr/www/mokpo_news/press_release/report_material?idx={id}&mode=view",
    idPattern: /idx=(\d+)/,
    selectors: MOKPO_SELECTORS,
    paginationParam: "page",
  },
  {
    id: "yeosu",
    name: "여수시청",
    type: "jeonnam-si",
    listUrl: "https://www.yeosu.go.kr/www/govt/news/release",
    detailUrlTemplate: "https://www.yeosu.go.kr/www/govt/news/release/press?idx={id}&mode=view",
    idPattern: /idx=(\d+)/,
    selectors: JEONNAM_SI_SELECTORS,
    paginationParam: "page",
  },
  {
    id: "suncheon",
    name: "순천시청",
    type: "suncheon",
    listUrl: "https://www.suncheon.go.kr/kr/news/0006/0001/",
    detailUrlTemplate: "https://www.suncheon.go.kr/kr/news/0006/0001/?mode=view&seq={id}",
    idPattern: /seq=(\d+)/,
    selectors: SUNCHEON_SELECTORS,
    paginationParam: "pageNo",
  },
  {
    id: "naju",
    name: "나주시청",
    type: "jeonnam-si",
    listUrl: "https://www.naju.go.kr/www/administration/reporting",
    detailUrlTemplate: "https://www.naju.go.kr/www/administration/reporting/coverage?idx={id}&mode=view",
    idPattern: /idx=(\d+)/,
    selectors: JEONNAM_SI_SELECTORS,
    paginationParam: "page",
  },
  {
    id: "gwangyang",
    name: "광양시청",
    type: "gwangju-es",
    listUrl: "https://gwangyang.go.kr/kor/board.es?mid=a11007000000&bid=0057",
    detailUrlTemplate: "https://gwangyang.go.kr/kor/board.es?mid=a11007000000&bid=0057&act=view&list_no={id}",
    idPattern: /list_no=(\d+)/,
    selectors: GWANGJU_ES_SELECTORS,
    paginationParam: "nPage",
  },
  {
    id: "damyang",
    name: "담양군청",
    type: "damyang",
    listUrl: "https://www.damyang.go.kr/board/list?boardId=BBS_0000007&domainId=DOM_0000001&menuCd=DOM_000000190001005001&contentsSid=12",
    detailUrlTemplate: "https://www.damyang.go.kr/board/detail?boardId=BBS_0000007&domainId=DOM_0000001&menuCd=DOM_000000190001005001&contentsSid=12&dataSid={id}",
    idPattern: /dataSid=(\d+)/,
    selectors: DAMYANG_SELECTORS,
    paginationParam: "pageIndex",
  },
  {
    id: "gokseong",
    name: "곡성군청",
    type: "gokseong",
    listUrl: "https://www.gokseong.go.kr/kr/board/list.do?bbsId=BBS_000000000000151&menuNo=102001002000",
    detailUrlTemplate: "https://www.gokseong.go.kr/kr/board/view.do?bbsId=BBS_000000000000151&menuNo=102001002000&nttId={id}",
    idPattern: /nttId=(\d+)/,
    selectors: GOKSEONG_SELECTORS,
  },
  {
    id: "gurye",
    name: "구례군청",
    type: "gurye",
    listUrl: "https://www.gurye.go.kr/board/list.do?bbsId=BBS_0000000000000300&menuNo=115004006000",
    detailUrlTemplate: "https://www.gurye.go.kr/board/view.do?bbsId=BBS_0000000000000300&menuNo=115004006000&nttId={id}",
    idPattern: /nttId=(\d+)/,
    selectors: GOKSEONG_SELECTORS,
  },
  {
    id: "goheung",
    name: "고흥군청",
    type: "gwangju-do",
    listUrl: "https://www.goheung.go.kr/boardList.do?boardId=BD_00025&pageId=www102",
    detailUrlTemplate: "https://www.goheung.go.kr/boardView.do?boardId=BD_00025&pageId=www102&seq={id}",
    idPattern: /seq=(\d+)/,
    selectors: GWANGJU_DO_SELECTORS,
    paginationParam: "pageIndex",
  },
  {
    id: "boseong",
    name: "보성군청",
    type: "boseong",
    listUrl: "https://www.boseong.go.kr/www/open_administration/city_news/press_release",
    detailUrlTemplate: "https://www.boseong.go.kr/www/open_administration/city_news/press_release?idx={id}&mode=view",
    idPattern: /idx=(\d+)/,
    selectors: JEONNAM_SI_SELECTORS,
    paginationParam: "pageNo",
  },
  {
    id: "hwasun",
    name: "화순군청",
    type: "hwasun",
    listUrl: "https://www.hwasun.go.kr/board.do?M=020102000000&S=S01&b_code=0000000002",
    detailUrlTemplate: "https://www.hwasun.go.kr/board.do?S=S01&M=020102000000&b_code=0000000002&act=view&list_no={id}",
    idPattern: /list_no=(\d+)/,
    selectors: HWASUN_SELECTORS,
  },
  {
    id: "jangheung",
    name: "장흥군청",
    type: "wando",
    listUrl: "https://www.jangheung.go.kr/jares/community/press",
    detailUrlTemplate: "https://www.jangheung.go.kr/jares/community/press?idx={id}&mode=view",
    idPattern: /idx=(\d+)/,
    selectors: WANDO_SELECTORS,
  },
  {
    id: "gangjin",
    name: "강진군청",
    type: "gangjin",
    listUrl: "https://www.gangjin.go.kr/www/government/news/press",
    detailUrlTemplate: "https://www.gangjin.go.kr/www/government/news/press?idx={id}&mode=view",
    idPattern: /idx=(\d+)/,
    selectors: JEONNAM_SI_SELECTORS,
    paginationParam: "pageNo",
  },
  {
    id: "haenam",
    name: "해남군청",
    type: "haenam",
    listUrl: "https://www.haenam.go.kr/planweb/board/list.9is?contentUid=18e3368f5d745106015d877ab2850a94&boardUid=18e3368f5fb80fdc015fdc4c2ac203e7",
    detailUrlTemplate: "https://www.haenam.go.kr/planweb/board/view.9is",
    idPattern: /nttId=(\d+)/,
    selectors: HAENAM_SELECTORS,
    paginationParam: "nowPageNum",
  },
  {
    id: "muan",
    name: "무안군청",
    type: "jeonnam-si",
    listUrl: "https://www.muan.go.kr/www/openmuan/new/report",
    detailUrlTemplate: "https://www.muan.go.kr/www/openmuan/new/report?idx={id}&mode=view",
    idPattern: /idx=(\d+)/,
    selectors: JEONNAM_SI_SELECTORS,
    paginationParam: "pageNo",
  },
  {
    id: "hampyeong",
    name: "함평군청",
    type: "gwangju-do",
    listUrl: "https://www.hampyeong.go.kr/boardList.do?boardId=NEWS&pageId=www275",
    detailUrlTemplate: "https://www.hampyeong.go.kr/boardView.do?boardId=NEWS&pageId=www275&seq={id}",
    idPattern: /seq=(\d+)/,
    selectors: GWANGJU_DO_SELECTORS,
    paginationParam: "pageIndex",
  },
  {
    id: "yeonggwang",
    name: "영광군청",
    type: "yeonggwang",
    listUrl: "https://www.yeonggwang.go.kr/bbs/?b_id=news_data&site=headquarter_new&mn=9056",
    detailUrlTemplate: "https://www.yeonggwang.go.kr/bbs/?b_id=news_data&site=headquarter_new&mn=9056&type=view&bs_idx={id}",
    idPattern: /bs_idx=(\d+)/,
    selectors: YEONGGWANG_SELECTORS,
  },
  {
    id: "jangseong",
    name: "장성군청",
    type: "jeonnam-si",
    listUrl: "https://www.jangseong.go.kr/home/www/news/jangseong/bodo",
    detailUrlTemplate: "https://www.jangseong.go.kr/home/www/news/jangseong/bodo/show/{id}",
    idPattern: /show\/(\d+)/,
    selectors: JEONNAM_SI_SELECTORS,
    paginationParam: "pageNo",
  },
  {
    id: "wando",
    name: "완도군청",
    type: "wando",
    listUrl: "https://www.wando.go.kr/wando/sub.cs?m=299",
    detailUrlTemplate: "https://www.wando.go.kr/wando/sub.cs?m=1023&nttId={id}&pBoardId=BBSMSTR_000000000036",
    idPattern: /nttId=(\d+)/,
    selectors: WANDO_SELECTORS,
  },
  {
    id: "shinan",
    name: "신안군청",
    type: "shinan",
    listUrl: "https://www.shinan.go.kr/home/www/openinfo/participation_07/participation_07_03/page.wscms",
    detailUrlTemplate: "https://www.shinan.go.kr/home/www/openinfo/participation_07/participation_07_03/show/{id}",
    idPattern: /show\/(\d+)/,
    selectors: JEONNAM_SI_SELECTORS,
    paginationParam: "pageNo",
  },
];

export const SITES_BY_ID = new Map(SITES.map((site) => [site.id, site]));
