UPDATE press_releases SET source = '광주시청' WHERE source = '광주시';
UPDATE press_releases SET source = '동구청' WHERE source = '광주 동구';
UPDATE press_releases SET source = '서구청' WHERE source = '광주 서구';
UPDATE press_releases SET source = '남구청' WHERE source = '광주 남구';
UPDATE press_releases SET source = '북구청' WHERE source = '광주 북구';
UPDATE press_releases SET source = '광산구청' WHERE source = '광주 광산구';
UPDATE press_releases SET source = '전라남도청' WHERE source = '전라남도';
UPDATE press_releases SET source = '목포시청' WHERE source = '목포시';
UPDATE press_releases SET source = '여수시청' WHERE source = '여수시';
UPDATE press_releases SET source = '순천시청' WHERE source = '순천시';
UPDATE press_releases SET source = '나주시청' WHERE source = '나주시';
UPDATE press_releases SET source = '광양시청' WHERE source = '광양시';
UPDATE press_releases SET source = '담양군청' WHERE source = '담양군';
UPDATE press_releases SET source = '곡성군청' WHERE source = '곡성군';
UPDATE press_releases SET source = '구례군청' WHERE source = '구례군';
UPDATE press_releases SET source = '고흥군청' WHERE source = '고흥군';
UPDATE press_releases SET source = '보성군청' WHERE source = '보성군';
UPDATE press_releases SET source = '화순군청' WHERE source = '화순군';
UPDATE press_releases SET source = '장흥군청' WHERE source = '장흥군';
UPDATE press_releases SET source = '강진군청' WHERE source = '강진군';
UPDATE press_releases SET source = '해남군청' WHERE source = '해남군';
UPDATE press_releases SET source = '무안군청' WHERE source = '무안군';
UPDATE press_releases SET source = '함평군청' WHERE source = '함평군';
UPDATE press_releases SET source = '영광군청' WHERE source = '영광군';
UPDATE press_releases SET source = '장성군청' WHERE source = '장성군';
UPDATE press_releases SET source = '완도군청' WHERE source = '완도군';
UPDATE press_releases SET source = '신안군청' WHERE source = '신안군';

UPDATE articles SET source = '광주시청' WHERE source = '광주시';
UPDATE articles SET source = '동구청' WHERE source = '광주 동구';
UPDATE articles SET source = '서구청' WHERE source = '광주 서구';
UPDATE articles SET source = '남구청' WHERE source = '광주 남구';
UPDATE articles SET source = '북구청' WHERE source = '광주 북구';
UPDATE articles SET source = '광산구청' WHERE source = '광주 광산구';
UPDATE articles SET source = '전라남도청' WHERE source = '전라남도';
UPDATE articles SET source = '목포시청' WHERE source = '목포시';
UPDATE articles SET source = '여수시청' WHERE source = '여수시';
UPDATE articles SET source = '순천시청' WHERE source = '순천시';
UPDATE articles SET source = '나주시청' WHERE source = '나주시';
UPDATE articles SET source = '광양시청' WHERE source = '광양시';
UPDATE articles SET source = '담양군청' WHERE source = '담양군';
UPDATE articles SET source = '곡성군청' WHERE source = '곡성군';
UPDATE articles SET source = '구례군청' WHERE source = '구례군';
UPDATE articles SET source = '고흥군청' WHERE source = '고흥군';
UPDATE articles SET source = '보성군청' WHERE source = '보성군';
UPDATE articles SET source = '화순군청' WHERE source = '화순군';
UPDATE articles SET source = '장흥군청' WHERE source = '장흥군';
UPDATE articles SET source = '강진군청' WHERE source = '강진군';
UPDATE articles SET source = '해남군청' WHERE source = '해남군';
UPDATE articles SET source = '무안군청' WHERE source = '무안군';
UPDATE articles SET source = '함평군청' WHERE source = '함평군';
UPDATE articles SET source = '영광군청' WHERE source = '영광군';
UPDATE articles SET source = '장성군청' WHERE source = '장성군';
UPDATE articles SET source = '완도군청' WHERE source = '완도군';
UPDATE articles SET source = '신안군청' WHERE source = '신안군';
